question_data = [
    {"category": "Science: Computers",
     "type": "boolean", "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Generally, which component of a computer draws the most power?", "correct_answer": "Video Card",
     "incorrect_answers": ["Hard Drive", "Processor", "Power Supply"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?",
     "correct_answer": "&lt;marquee&gt;&lt;\/marquee&gt;",
     "incorrect_answers": ["&lt;scroll&gt;&lt;\/scroll&gt;", "&lt;move&gt;&lt;\/move&gt;",
                           "&lt;slide&gt;&lt;\/slide&gt;"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of these is not a key value of Agile software development?",
     "correct_answer": "Comprehensive documentation",
     "incorrect_answers": ["Individuals and interactions", "Customer collaboration", "Responding to change"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Who invented the &quot;Spanning Tree Protocol&quot;?", "correct_answer": "Radia Perlman",
     "incorrect_answers": ["Paul Vixie", "Vint Cerf", "Michael Roberts"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:",
     "correct_answer": "A&#039; + B&#039;",
     "incorrect_answers": ["A&#039;B + B&#039;A", "A&#039;B&#039;", "AB&#039; + AB"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "The acronym &quot;RIP&quot; stands for which of these?",
     "correct_answer": "Routing Information Protocol",
     "incorrect_answers": ["Runtime Instance Processes", "Regular Interval Processes", "Routine Inspection Protocol"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What language does Node.js use?", "correct_answer": "JavaScript",
     "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does the computer software acronym JVM stand for?", "correct_answer": "Java Virtual Machine",
     "incorrect_answers": ["Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine"]}
]
